// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chat.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (
  session_id,
  role,
  status,
  content,
  provider_name,
  model
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, session_id, role, status, content, provider_name, model, created_at, updated_at
`

type CreateChatMessageParams struct {
	SessionID    int64             `json:"session_id"`
	Role         ChatMessageRole   `json:"role"`
	Status       ChatMessageStatus `json:"status"`
	Content      string            `json:"content"`
	ProviderName string            `json:"provider_name"`
	Model        string            `json:"model"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage,
		arg.SessionID,
		arg.Role,
		arg.Status,
		arg.Content,
		arg.ProviderName,
		arg.Model,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.ProviderName,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatSession = `-- name: CreateChatSession :one

INSERT INTO chat_sessions (
  user_id,
  title,
  provider_name
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, user_id, title, provider_name, summary, summary_through_id, created_at, updated_at
`

type CreateChatSessionParams struct {
	UserID       int64  `json:"user_id"`
	Title        string `json:"title"`
	ProviderName string `json:"provider_name"`
}

// Pentest chat. Every session query is scoped by user_id: sessions are
// private to their owner, and there is no admin view.
func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, createChatSession, arg.UserID, arg.Title, arg.ProviderName)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ProviderName,
		&i.Summary,
		&i.SummaryThroughID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatUsage = `-- name: CreateChatUsage :one
INSERT INTO chat_usage (
  user_id,
  kind,
  session_id,
  message_id,
  usage_in,
  usage_out,
  cost_in,
  cost_out
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, user_id, kind, session_id, message_id, usage_in, usage_out, cost_in, cost_out, created_at
`

type CreateChatUsageParams struct {
	UserID    int64         `json:"user_id"`
	Kind      ChatUsageKind `json:"kind"`
	SessionID sql.NullInt64 `json:"session_id"`
	MessageID sql.NullInt64 `json:"message_id"`
	UsageIn   int64         `json:"usage_in"`
	UsageOut  int64         `json:"usage_out"`
	CostIn    float64       `json:"cost_in"`
	CostOut   float64       `json:"cost_out"`
}

func (q *Queries) CreateChatUsage(ctx context.Context, arg CreateChatUsageParams) (ChatUsage, error) {
	row := q.db.QueryRowContext(ctx, createChatUsage,
		arg.UserID,
		arg.Kind,
		arg.SessionID,
		arg.MessageID,
		arg.UsageIn,
		arg.UsageOut,
		arg.CostIn,
		arg.CostOut,
	)
	var i ChatUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SessionID,
		&i.MessageID,
		&i.UsageIn,
		&i.UsageOut,
		&i.CostIn,
		&i.CostOut,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChatUsage = `-- name: DeleteChatUsage :exec
DELETE FROM chat_usage
WHERE id = $1
`

// A reply that failed before generating anything gives the user their
// message (and its token reservation) back.
func (q *Queries) DeleteChatUsage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChatUsage, id)
	return err
}

const deleteUserChatSession = `-- name: DeleteUserChatSession :one
DELETE FROM chat_sessions
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, provider_name, summary, summary_through_id, created_at, updated_at
`

type DeleteUserChatSessionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteUserChatSession(ctx context.Context, arg DeleteUserChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, deleteUserChatSession, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ProviderName,
		&i.Summary,
		&i.SummaryThroughID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failStreamingChatMessages = `-- name: FailStreamingChatMessages :exec
UPDATE chat_messages
SET status = 'error'
WHERE status = 'streaming'
`

// Replies cannot outlive the process that streams them: anything still
// streaming at startup was cut off by a restart.
func (q *Queries) FailStreamingChatMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, failStreamingChatMessages)
	return err
}

const finishChatMessage = `-- name: FinishChatMessage :one
UPDATE chat_messages
SET status = $2, content = $3, model = $4
WHERE id = $1 AND status = 'streaming'
RETURNING id, session_id, role, status, content, provider_name, model, created_at, updated_at
`

type FinishChatMessageParams struct {
	ID      int64             `json:"id"`
	Status  ChatMessageStatus `json:"status"`
	Content string            `json:"content"`
	Model   string            `json:"model"`
}

// Final write of a reply. Guarded on 'streaming' so a stop and a finish
// racing each other cannot overwrite the one that landed first.
func (q *Queries) FinishChatMessage(ctx context.Context, arg FinishChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, finishChatMessage,
		arg.ID,
		arg.Status,
		arg.Content,
		arg.Model,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.ProviderName,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, session_id, role, status, content, provider_name, model, created_at, updated_at FROM chat_messages
WHERE session_id = $1
ORDER BY id ASC
`

func (q *Queries) GetChatMessages(ctx context.Context, sessionID int64) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Status,
			&i.Content,
			&i.ProviderName,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesAfter = `-- name: GetChatMessagesAfter :many
SELECT id, session_id, role, status, content, provider_name, model, created_at, updated_at FROM chat_messages
WHERE session_id = $1 AND id > $2
ORDER BY id ASC
`

type GetChatMessagesAfterParams struct {
	SessionID int64 `json:"session_id"`
	ID        int64 `json:"id"`
}

// Messages not yet folded into the session summary, oldest first.
func (q *Queries) GetChatMessagesAfter(ctx context.Context, arg GetChatMessagesAfterParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessagesAfter, arg.SessionID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Status,
			&i.Content,
			&i.ProviderName,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChatMessage = `-- name: GetUserChatMessage :one
SELECT m.id, m.session_id, m.role, m.status, m.content, m.provider_name, m.model, m.created_at, m.updated_at FROM chat_messages m
INNER JOIN chat_sessions s ON m.session_id = s.id
WHERE m.id = $1 AND s.user_id = $2
`

type GetUserChatMessageParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetUserChatMessage(ctx context.Context, arg GetUserChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getUserChatMessage, arg.ID, arg.UserID)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.ProviderName,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserChatReplyStats = `-- name: GetUserChatReplyStats :one
SELECT
  COUNT(*)::BIGINT AS count,
  COALESCE(MIN(created_at), NOW())::TIMESTAMPTZ AS oldest
FROM chat_usage
WHERE user_id = $1 AND kind = 'reply' AND created_at > $2
`

type GetUserChatReplyStatsParams struct {
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetUserChatReplyStatsRow struct {
	Count  int64     `json:"count"`
	Oldest time.Time `json:"oldest"`
}

func (q *Queries) GetUserChatReplyStats(ctx context.Context, arg GetUserChatReplyStatsParams) (GetUserChatReplyStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserChatReplyStats, arg.UserID, arg.CreatedAt)
	var i GetUserChatReplyStatsRow
	err := row.Scan(&i.Count, &i.Oldest)
	return i, err
}

const getUserChatSession = `-- name: GetUserChatSession :one
SELECT id, user_id, title, provider_name, summary, summary_through_id, created_at, updated_at FROM chat_sessions
WHERE id = $1 AND user_id = $2
`

type GetUserChatSessionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetUserChatSession(ctx context.Context, arg GetUserChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getUserChatSession, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ProviderName,
		&i.Summary,
		&i.SummaryThroughID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserChatSessions = `-- name: GetUserChatSessions :many
SELECT id, user_id, title, provider_name, summary, summary_through_id, created_at, updated_at FROM chat_sessions
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetUserChatSessions(ctx context.Context, userID int64) ([]ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, getUserChatSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.ProviderName,
			&i.Summary,
			&i.SummaryThroughID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChatTokenStats = `-- name: GetUserChatTokenStats :one
SELECT
  COALESCE(SUM(usage_in + usage_out), 0)::BIGINT AS tokens,
  COALESCE(MIN(created_at), NOW())::TIMESTAMPTZ AS oldest
FROM chat_usage
WHERE user_id = $1 AND created_at > $2
`

type GetUserChatTokenStatsParams struct {
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetUserChatTokenStatsRow struct {
	Tokens int64     `json:"tokens"`
	Oldest time.Time `json:"oldest"`
}

func (q *Queries) GetUserChatTokenStats(ctx context.Context, arg GetUserChatTokenStatsParams) (GetUserChatTokenStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserChatTokenStats, arg.UserID, arg.CreatedAt)
	var i GetUserChatTokenStatsRow
	err := row.Scan(&i.Tokens, &i.Oldest)
	return i, err
}

const replaceChatSessionTitle = `-- name: ReplaceChatSessionTitle :one
UPDATE chat_sessions
SET title = $3
WHERE id = $1 AND title = $2
RETURNING id, user_id, title, provider_name, summary, summary_through_id, created_at, updated_at
`

type ReplaceChatSessionTitleParams struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Title_2 string `json:"title_2"`
}

// Replaces the placeholder title with a generated one, unless the user
// renamed the session in the meantime.
func (q *Queries) ReplaceChatSessionTitle(ctx context.Context, arg ReplaceChatSessionTitleParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, replaceChatSessionTitle, arg.ID, arg.Title, arg.Title_2)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ProviderName,
		&i.Summary,
		&i.SummaryThroughID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchChatSession = `-- name: TouchChatSession :one
UPDATE chat_sessions
SET provider_name = $2
WHERE id = $1
RETURNING id, user_id, title, provider_name, summary, summary_through_id, created_at, updated_at
`

type TouchChatSessionParams struct {
	ID           int64  `json:"id"`
	ProviderName string `json:"provider_name"`
}

// Records the provider of the latest message; also bumps updated_at so the
// session moves to the top of the history list.
func (q *Queries) TouchChatSession(ctx context.Context, arg TouchChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, touchChatSession, arg.ID, arg.ProviderName)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ProviderName,
		&i.Summary,
		&i.SummaryThroughID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatSessionSummary = `-- name: UpdateChatSessionSummary :one
UPDATE chat_sessions
SET summary = $2, summary_through_id = $3
WHERE id = $1
RETURNING id, user_id, title, provider_name, summary, summary_through_id, created_at, updated_at
`

type UpdateChatSessionSummaryParams struct {
	ID               int64  `json:"id"`
	Summary          string `json:"summary"`
	SummaryThroughID int64  `json:"summary_through_id"`
}

func (q *Queries) UpdateChatSessionSummary(ctx context.Context, arg UpdateChatSessionSummaryParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, updateChatSessionSummary, arg.ID, arg.Summary, arg.SummaryThroughID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ProviderName,
		&i.Summary,
		&i.SummaryThroughID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatUsage = `-- name: UpdateChatUsage :exec
UPDATE chat_usage
SET usage_in = $2, usage_out = $3, cost_in = $4, cost_out = $5
WHERE id = $1
`

type UpdateChatUsageParams struct {
	ID       int64   `json:"id"`
	UsageIn  int64   `json:"usage_in"`
	UsageOut int64   `json:"usage_out"`
	CostIn   float64 `json:"cost_in"`
	CostOut  float64 `json:"cost_out"`
}

// Addressed by the ledger row's own id, not message_id: deleting the chat
// mid-reply nulls message_id, and the reply's tokens must still be counted.
func (q *Queries) UpdateChatUsage(ctx context.Context, arg UpdateChatUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateChatUsage,
		arg.ID,
		arg.UsageIn,
		arg.UsageOut,
		arg.CostIn,
		arg.CostOut,
	)
	return err
}

const updateUserChatSessionTitle = `-- name: UpdateUserChatSessionTitle :one
UPDATE chat_sessions
SET title = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, provider_name, summary, summary_through_id, created_at, updated_at
`

type UpdateUserChatSessionTitleParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Title  string `json:"title"`
}

func (q *Queries) UpdateUserChatSessionTitle(ctx context.Context, arg UpdateUserChatSessionTitleParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, updateUserChatSessionTitle, arg.ID, arg.UserID, arg.Title)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ProviderName,
		&i.Summary,
		&i.SummaryThroughID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
