// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: domains.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countActiveDomainsForUser = `-- name: CountActiveDomainsForUser :one
SELECT COUNT(*)::bigint
FROM domains
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status IN ('created', 'classifying', 'running')
`

func (q *Queries) CountActiveDomainsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDomainsForUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (
  user_id, name, target_type, status, detection_metadata
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, name, target_type, status, detection_metadata, created_at, updated_at, deleted_at, scope, box
`

type CreateDomainParams struct {
	UserID            int64           `json:"user_id"`
	Name              string          `json:"name"`
	TargetType        TargetType      `json:"target_type"`
	Status            DomainStatus    `json:"status"`
	DetectionMetadata json.RawMessage `json:"detection_metadata"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.UserID,
		arg.Name,
		arg.TargetType,
		arg.Status,
		arg.DetectionMetadata,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetType,
		&i.Status,
		&i.DetectionMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.Box,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :one
UPDATE domains
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, name, target_type, status, detection_metadata, created_at, updated_at, deleted_at, scope, box
`

func (q *Queries) DeleteDomain(ctx context.Context, id int64) (Domain, error) {
	row := q.db.QueryRowContext(ctx, deleteDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetType,
		&i.Status,
		&i.DetectionMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.Box,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
SELECT id, user_id, name, target_type, status, detection_metadata, created_at, updated_at, deleted_at, scope, box FROM domains
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDomain(ctx context.Context, id int64) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetType,
		&i.Status,
		&i.DetectionMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.Box,
	)
	return i, err
}

const getDomains = `-- name: GetDomains :many
SELECT id, user_id, name, target_type, status, detection_metadata, created_at, updated_at, deleted_at, scope, box FROM domains
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, getDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetType,
			&i.Status,
			&i.DetectionMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Scope,
			&i.Box,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDomain = `-- name: GetUserDomain :one
SELECT id, user_id, name, target_type, status, detection_metadata, created_at, updated_at, deleted_at, scope, box FROM domains
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetUserDomainParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetUserDomain(ctx context.Context, arg GetUserDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getUserDomain, arg.ID, arg.UserID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetType,
		&i.Status,
		&i.DetectionMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.Box,
	)
	return i, err
}

const getUserDomains = `-- name: GetUserDomains :many
SELECT id, user_id, name, target_type, status, detection_metadata, created_at, updated_at, deleted_at, scope, box FROM domains
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetUserDomains(ctx context.Context, userID int64) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, getUserDomains, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetType,
			&i.Status,
			&i.DetectionMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Scope,
			&i.Box,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainScopeBox = `-- name: SetDomainScopeBox :exec
UPDATE domains
SET scope = $2, box = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type SetDomainScopeBoxParams struct {
	ID    int64          `json:"id"`
	Scope sql.NullString `json:"scope"`
	Box   sql.NullString `json:"box"`
}

func (q *Queries) SetDomainScopeBox(ctx context.Context, arg SetDomainScopeBoxParams) error {
	_, err := q.db.ExecContext(ctx, setDomainScopeBox, arg.ID, arg.Scope, arg.Box)
	return err
}

const updateDomainDetectionMetadata = `-- name: UpdateDomainDetectionMetadata :one
UPDATE domains
SET target_type = $2, detection_metadata = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, name, target_type, status, detection_metadata, created_at, updated_at, deleted_at, scope, box
`

type UpdateDomainDetectionMetadataParams struct {
	ID                int64           `json:"id"`
	TargetType        TargetType      `json:"target_type"`
	DetectionMetadata json.RawMessage `json:"detection_metadata"`
}

func (q *Queries) UpdateDomainDetectionMetadata(ctx context.Context, arg UpdateDomainDetectionMetadataParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, updateDomainDetectionMetadata, arg.ID, arg.TargetType, arg.DetectionMetadata)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetType,
		&i.Status,
		&i.DetectionMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.Box,
	)
	return i, err
}

const updateDomainStatus = `-- name: UpdateDomainStatus :one
UPDATE domains
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, name, target_type, status, detection_metadata, created_at, updated_at, deleted_at, scope, box
`

type UpdateDomainStatusParams struct {
	ID     int64        `json:"id"`
	Status DomainStatus `json:"status"`
}

func (q *Queries) UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, updateDomainStatus, arg.ID, arg.Status)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetType,
		&i.Status,
		&i.DetectionMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Scope,
		&i.Box,
	)
	return i, err
}
