// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flow_template_requests.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const approveCreateFlowTemplateRequest = `-- name: ApproveCreateFlowTemplateRequest :one
WITH new_template AS (
  SELECT nextval(pg_get_serial_sequence('flow_templates', 'id')) AS id
), approved AS (
  UPDATE flow_template_requests
  SET
    status = 'approved',
    template_id = (SELECT new_template.id FROM new_template),
    review_note = $1,
    reviewed_by = $2::BIGINT,
    reviewed_at = CURRENT_TIMESTAMP
  WHERE flow_template_requests.id = $3
    AND kind = 'create'
    AND revision = $4
    AND status = 'pending'
  RETURNING id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at
)
INSERT INTO flow_templates (id, user_id, title, text, target_types)
OVERRIDING SYSTEM VALUE
SELECT approved.template_id, approved.requester_id, approved.title, approved.text, approved.target_types
FROM approved
RETURNING id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at
`

type ApproveCreateFlowTemplateRequestParams struct {
	ReviewNote sql.NullString `json:"review_note"`
	ReviewerID int64          `json:"reviewer_id"`
	ID         int64          `json:"id"`
	Revision   int32          `json:"revision"`
}

// Approving a new template: mark the request approved and publish the
// template atomically. The template id is drawn up front so the request can
// link to the template it produced within the same statement.
func (q *Queries) ApproveCreateFlowTemplateRequest(ctx context.Context, arg ApproveCreateFlowTemplateRequestParams) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, approveCreateFlowTemplateRequest,
		arg.ReviewNote,
		arg.ReviewerID,
		arg.ID,
		arg.Revision,
	)
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
		&i.Version,
		&i.ArchivedAt,
	)
	return i, err
}

const approveUpdateFlowTemplateRequest = `-- name: ApproveUpdateFlowTemplateRequest :one
WITH req AS (
  SELECT r.id, r.template_id, r.title, r.text, r.target_types
  FROM flow_template_requests r
  WHERE r.id = $1
    AND r.kind = 'update'
    AND r.revision = $2
    AND r.status = 'pending'
  FOR UPDATE
), updated AS (
  UPDATE flow_templates
  SET
    title = req.title,
    text = req.text,
    target_types = req.target_types,
    version = flow_templates.version + 1
  FROM req
  WHERE flow_templates.id = req.template_id
    AND flow_templates.archived_at IS NULL
    AND flow_templates.version = $3
  RETURNING flow_templates.id, flow_templates.user_id, flow_templates.title, flow_templates.text, flow_templates.created_at, flow_templates.updated_at, flow_templates.target_types, flow_templates.system_owned, flow_templates.version, flow_templates.archived_at
), approved AS (
  UPDATE flow_template_requests
  SET
    status = 'approved',
    review_note = $4,
    reviewed_by = $5::BIGINT,
    reviewed_at = CURRENT_TIMESTAMP
  WHERE flow_template_requests.id = $1
    AND EXISTS (SELECT 1 FROM updated)
  RETURNING flow_template_requests.id
)
SELECT
  updated.id, updated.user_id, updated.title, updated.text, updated.created_at, updated.updated_at,
  updated.target_types, updated.system_owned, updated.version, updated.archived_at
FROM updated
`

type ApproveUpdateFlowTemplateRequestParams struct {
	ID              int64          `json:"id"`
	Revision        int32          `json:"revision"`
	TemplateVersion int32          `json:"template_version"`
	ReviewNote      sql.NullString `json:"review_note"`
	ReviewerID      int64          `json:"reviewer_id"`
}

type ApproveUpdateFlowTemplateRequestRow struct {
	ID          int64         `json:"id"`
	UserID      sql.NullInt64 `json:"user_id"`
	Title       string        `json:"title"`
	Text        string        `json:"text"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	TargetTypes []TargetType  `json:"target_types"`
	SystemOwned bool          `json:"system_owned"`
	Version     int32         `json:"version"`
	ArchivedAt  sql.NullTime  `json:"archived_at"`
}

// Approving an edit: the template is written first, guarded on its version
// (re-checked by Postgres after any row-lock wait), and the request is marked
// approved only if that write happened. A concurrent admin edit, archive,
// requester edit or second reviewer therefore makes this a no-op, never a
// half-applied approval.
func (q *Queries) ApproveUpdateFlowTemplateRequest(ctx context.Context, arg ApproveUpdateFlowTemplateRequestParams) (ApproveUpdateFlowTemplateRequestRow, error) {
	row := q.db.QueryRowContext(ctx, approveUpdateFlowTemplateRequest,
		arg.ID,
		arg.Revision,
		arg.TemplateVersion,
		arg.ReviewNote,
		arg.ReviewerID,
	)
	var i ApproveUpdateFlowTemplateRequestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
		&i.Version,
		&i.ArchivedAt,
	)
	return i, err
}

const countPendingFlowTemplateRequestsByRequester = `-- name: CountPendingFlowTemplateRequestsByRequester :one
SELECT COUNT(*)::BIGINT FROM flow_template_requests
WHERE requester_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingFlowTemplateRequestsByRequester(ctx context.Context, requesterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingFlowTemplateRequestsByRequester, requesterID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createFlowTemplateRequest = `-- name: CreateFlowTemplateRequest :one
INSERT INTO flow_template_requests (
  kind,
  template_id,
  requester_id,
  title,
  text,
  target_types,
  base_version
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at
`

type CreateFlowTemplateRequestParams struct {
	Kind        TemplateRequestKind `json:"kind"`
	TemplateID  sql.NullInt64       `json:"template_id"`
	RequesterID int64               `json:"requester_id"`
	Title       string              `json:"title"`
	Text        string              `json:"text"`
	TargetTypes []TargetType        `json:"target_types"`
	BaseVersion sql.NullInt32       `json:"base_version"`
}

func (q *Queries) CreateFlowTemplateRequest(ctx context.Context, arg CreateFlowTemplateRequestParams) (FlowTemplateRequest, error) {
	row := q.db.QueryRowContext(ctx, createFlowTemplateRequest,
		arg.Kind,
		arg.TemplateID,
		arg.RequesterID,
		arg.Title,
		arg.Text,
		pq.Array(arg.TargetTypes),
		arg.BaseVersion,
	)
	var i FlowTemplateRequest
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.TemplateID,
		&i.RequesterID,
		&i.Title,
		&i.Text,
		pq.Array(&i.TargetTypes),
		&i.Revision,
		&i.BaseVersion,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowTemplateRequest = `-- name: GetFlowTemplateRequest :one

SELECT id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at, requester_name, reviewer_name FROM flow_template_requests_view
WHERE id = $1 LIMIT 1
`

// Template requests: a user's proposed new template or edit to their own
// template, waiting for admin review. Every state transition is a single
// conditional statement (status/revision/version guards in the WHERE clause),
// so concurrent reviewers or a requester editing mid-review can never apply a
// decision to content the reviewer did not see.
func (q *Queries) GetFlowTemplateRequest(ctx context.Context, id int64) (FlowTemplateRequestsView, error) {
	row := q.db.QueryRowContext(ctx, getFlowTemplateRequest, id)
	var i FlowTemplateRequestsView
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.TemplateID,
		&i.RequesterID,
		&i.Title,
		&i.Text,
		pq.Array(&i.TargetTypes),
		&i.Revision,
		&i.BaseVersion,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequesterName,
		&i.ReviewerName,
	)
	return i, err
}

const getFlowTemplateRequests = `-- name: GetFlowTemplateRequests :many
SELECT id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at, requester_name, reviewer_name FROM flow_template_requests_view
ORDER BY (status = 'pending') DESC, updated_at DESC
`

func (q *Queries) GetFlowTemplateRequests(ctx context.Context) ([]FlowTemplateRequestsView, error) {
	rows, err := q.db.QueryContext(ctx, getFlowTemplateRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTemplateRequestsView
	for rows.Next() {
		var i FlowTemplateRequestsView
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.TemplateID,
			&i.RequesterID,
			&i.Title,
			&i.Text,
			pq.Array(&i.TargetTypes),
			&i.Revision,
			&i.BaseVersion,
			&i.ReviewNote,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterName,
			&i.ReviewerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowTemplateRequestsByRequester = `-- name: GetFlowTemplateRequestsByRequester :many
SELECT id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at, requester_name, reviewer_name FROM flow_template_requests_view
WHERE requester_id = $1
ORDER BY (status = 'pending') DESC, updated_at DESC
`

func (q *Queries) GetFlowTemplateRequestsByRequester(ctx context.Context, requesterID int64) ([]FlowTemplateRequestsView, error) {
	rows, err := q.db.QueryContext(ctx, getFlowTemplateRequestsByRequester, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTemplateRequestsView
	for rows.Next() {
		var i FlowTemplateRequestsView
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.TemplateID,
			&i.RequesterID,
			&i.Title,
			&i.Text,
			pq.Array(&i.TargetTypes),
			&i.Revision,
			&i.BaseVersion,
			&i.ReviewNote,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterName,
			&i.ReviewerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingFlowTemplateRequestByTemplate = `-- name: GetPendingFlowTemplateRequestByTemplate :one
SELECT id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at, requester_name, reviewer_name FROM flow_template_requests_view
WHERE template_id = $1 AND status = 'pending' LIMIT 1
`

func (q *Queries) GetPendingFlowTemplateRequestByTemplate(ctx context.Context, templateID sql.NullInt64) (FlowTemplateRequestsView, error) {
	row := q.db.QueryRowContext(ctx, getPendingFlowTemplateRequestByTemplate, templateID)
	var i FlowTemplateRequestsView
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.TemplateID,
		&i.RequesterID,
		&i.Title,
		&i.Text,
		pq.Array(&i.TargetTypes),
		&i.Revision,
		&i.BaseVersion,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequesterName,
		&i.ReviewerName,
	)
	return i, err
}

const rejectFlowTemplateRequest = `-- name: RejectFlowTemplateRequest :one
UPDATE flow_template_requests
SET
  status = 'rejected',
  review_note = $1::TEXT,
  reviewed_by = $2::BIGINT,
  reviewed_at = CURRENT_TIMESTAMP
WHERE id = $3 AND revision = $4 AND status = 'pending'
RETURNING id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at
`

type RejectFlowTemplateRequestParams struct {
	ReviewNote string `json:"review_note"`
	ReviewerID int64  `json:"reviewer_id"`
	ID         int64  `json:"id"`
	Revision   int32  `json:"revision"`
}

func (q *Queries) RejectFlowTemplateRequest(ctx context.Context, arg RejectFlowTemplateRequestParams) (FlowTemplateRequest, error) {
	row := q.db.QueryRowContext(ctx, rejectFlowTemplateRequest,
		arg.ReviewNote,
		arg.ReviewerID,
		arg.ID,
		arg.Revision,
	)
	var i FlowTemplateRequest
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.TemplateID,
		&i.RequesterID,
		&i.Title,
		&i.Text,
		pq.Array(&i.TargetTypes),
		&i.Revision,
		&i.BaseVersion,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingFlowTemplateRequest = `-- name: UpdatePendingFlowTemplateRequest :one
UPDATE flow_template_requests
SET
  title = $4,
  text = $5,
  target_types = $6,
  base_version = $7,
  revision = revision + 1
WHERE id = $1 AND requester_id = $2 AND revision = $3 AND status = 'pending'
RETURNING id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at
`

type UpdatePendingFlowTemplateRequestParams struct {
	ID          int64         `json:"id"`
	RequesterID int64         `json:"requester_id"`
	Revision    int32         `json:"revision"`
	Title       string        `json:"title"`
	Text        string        `json:"text"`
	TargetTypes []TargetType  `json:"target_types"`
	BaseVersion sql.NullInt32 `json:"base_version"`
}

func (q *Queries) UpdatePendingFlowTemplateRequest(ctx context.Context, arg UpdatePendingFlowTemplateRequestParams) (FlowTemplateRequest, error) {
	row := q.db.QueryRowContext(ctx, updatePendingFlowTemplateRequest,
		arg.ID,
		arg.RequesterID,
		arg.Revision,
		arg.Title,
		arg.Text,
		pq.Array(arg.TargetTypes),
		arg.BaseVersion,
	)
	var i FlowTemplateRequest
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.TemplateID,
		&i.RequesterID,
		&i.Title,
		&i.Text,
		pq.Array(&i.TargetTypes),
		&i.Revision,
		&i.BaseVersion,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawFlowTemplateRequest = `-- name: WithdrawFlowTemplateRequest :one
UPDATE flow_template_requests
SET status = 'withdrawn'
WHERE id = $1 AND requester_id = $2 AND status = 'pending'
RETURNING id, kind, status, template_id, requester_id, title, text, target_types, revision, base_version, review_note, reviewed_by, reviewed_at, created_at, updated_at
`

type WithdrawFlowTemplateRequestParams struct {
	ID          int64 `json:"id"`
	RequesterID int64 `json:"requester_id"`
}

func (q *Queries) WithdrawFlowTemplateRequest(ctx context.Context, arg WithdrawFlowTemplateRequestParams) (FlowTemplateRequest, error) {
	row := q.db.QueryRowContext(ctx, withdrawFlowTemplateRequest, arg.ID, arg.RequesterID)
	var i FlowTemplateRequest
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.TemplateID,
		&i.RequesterID,
		&i.Title,
		&i.Text,
		pq.Array(&i.TargetTypes),
		&i.Revision,
		&i.BaseVersion,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
