// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flow_templates.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const createFlowTemplate = `-- name: CreateFlowTemplate :one
INSERT INTO flow_templates (
  user_id,
  title,
  text,
  target_types
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, user_id, title, text, created_at, updated_at, target_types, system_owned
`

type CreateFlowTemplateParams struct {
	UserID      int64        `json:"user_id"`
	Title       string       `json:"title"`
	Text        string       `json:"text"`
	TargetTypes []TargetType `json:"target_types"`
}

func (q *Queries) CreateFlowTemplate(ctx context.Context, arg CreateFlowTemplateParams) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, createFlowTemplate,
		arg.UserID,
		arg.Title,
		arg.Text,
		pq.Array(arg.TargetTypes),
	)
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
	)
	return i, err
}

const deleteFlowTemplate = `-- name: DeleteFlowTemplate :exec
DELETE FROM flow_templates
WHERE id = $1 AND user_id = $2
`

type DeleteFlowTemplateParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteFlowTemplate(ctx context.Context, arg DeleteFlowTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteFlowTemplate, arg.ID, arg.UserID)
	return err
}

const getDefaultFlowTemplatesByTargetType = `-- name: GetDefaultFlowTemplatesByTargetType :many
SELECT id, user_id, title, text, created_at, updated_at, target_types, system_owned FROM flow_templates
WHERE (user_id = $1 OR system_owned = true)
  AND $2::TARGET_TYPE = ANY(target_types)
ORDER BY system_owned DESC, created_at DESC
`

type GetDefaultFlowTemplatesByTargetTypeParams struct {
	UserID  int64      `json:"user_id"`
	Column2 TargetType `json:"column_2"`
}

func (q *Queries) GetDefaultFlowTemplatesByTargetType(ctx context.Context, arg GetDefaultFlowTemplatesByTargetTypeParams) ([]FlowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getDefaultFlowTemplatesByTargetType, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTemplate
	for rows.Next() {
		var i FlowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.TargetTypes),
			&i.SystemOwned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowTemplate = `-- name: GetFlowTemplate :one
SELECT id, user_id, title, text, created_at, updated_at, target_types, system_owned FROM flow_templates
WHERE id = $1 AND (user_id = $2 OR system_owned = true) LIMIT 1
`

type GetFlowTemplateParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetFlowTemplate(ctx context.Context, arg GetFlowTemplateParams) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, getFlowTemplate, arg.ID, arg.UserID)
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
	)
	return i, err
}

const getFlowTemplatesByTargetType = `-- name: GetFlowTemplatesByTargetType :many
SELECT id, user_id, title, text, created_at, updated_at, target_types, system_owned FROM flow_templates
WHERE (user_id = $1 OR system_owned = true)
  AND $2::TARGET_TYPE = ANY(target_types)
ORDER BY system_owned DESC, created_at DESC
`

type GetFlowTemplatesByTargetTypeParams struct {
	UserID  int64      `json:"user_id"`
	Column2 TargetType `json:"column_2"`
}

func (q *Queries) GetFlowTemplatesByTargetType(ctx context.Context, arg GetFlowTemplatesByTargetTypeParams) ([]FlowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getFlowTemplatesByTargetType, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTemplate
	for rows.Next() {
		var i FlowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.TargetTypes),
			&i.SystemOwned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowTemplatesByUserID = `-- name: GetFlowTemplatesByUserID :many
SELECT id, user_id, title, text, created_at, updated_at, target_types, system_owned FROM flow_templates
WHERE user_id = $1 OR system_owned = true
ORDER BY system_owned DESC, created_at DESC
`

func (q *Queries) GetFlowTemplatesByUserID(ctx context.Context, userID int64) ([]FlowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getFlowTemplatesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTemplate
	for rows.Next() {
		var i FlowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.TargetTypes),
			&i.SystemOwned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowTemplate = `-- name: UpdateFlowTemplate :one
UPDATE flow_templates
SET
  title = $3,
  text = $4
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, text, created_at, updated_at, target_types, system_owned
`

type UpdateFlowTemplateParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Title  string `json:"title"`
	Text   string `json:"text"`
}

func (q *Queries) UpdateFlowTemplate(ctx context.Context, arg UpdateFlowTemplateParams) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateFlowTemplate,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Text,
	)
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
	)
	return i, err
}

const updateFlowTemplateTargetTypes = `-- name: UpdateFlowTemplateTargetTypes :one
UPDATE flow_templates
SET
  target_types = $2
WHERE id = $1
RETURNING id, user_id, title, text, created_at, updated_at, target_types, system_owned
`

type UpdateFlowTemplateTargetTypesParams struct {
	ID          int64        `json:"id"`
	TargetTypes []TargetType `json:"target_types"`
}

func (q *Queries) UpdateFlowTemplateTargetTypes(ctx context.Context, arg UpdateFlowTemplateTargetTypesParams) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateFlowTemplateTargetTypes, arg.ID, pq.Array(arg.TargetTypes))
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
	)
	return i, err
}
