// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flow_templates.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const archiveFlowTemplate = `-- name: ArchiveFlowTemplate :one
WITH archived AS (
  UPDATE flow_templates
  SET archived_at = CURRENT_TIMESTAMP
  WHERE flow_templates.id = $1 AND archived_at IS NULL
  RETURNING id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at
), closed AS (
  UPDATE flow_template_requests
  SET
    status = 'closed',
    review_note = 'The template was deleted by an administrator.',
    reviewed_by = $2::BIGINT,
    reviewed_at = CURRENT_TIMESTAMP
  WHERE template_id IN (SELECT archived.id FROM archived) AND status = 'pending'
  RETURNING flow_template_requests.id
)
SELECT
  archived.id, archived.user_id, archived.title, archived.text, archived.created_at, archived.updated_at,
  archived.target_types, archived.system_owned, archived.version, archived.archived_at,
  COALESCE((SELECT closed.id FROM closed LIMIT 1), 0)::BIGINT AS closed_request_id
FROM archived
`

type ArchiveFlowTemplateParams struct {
	ID         int64 `json:"id"`
	ReviewerID int64 `json:"reviewer_id"`
}

type ArchiveFlowTemplateRow struct {
	ID              int64         `json:"id"`
	UserID          sql.NullInt64 `json:"user_id"`
	Title           string        `json:"title"`
	Text            string        `json:"text"`
	CreatedAt       sql.NullTime  `json:"created_at"`
	UpdatedAt       sql.NullTime  `json:"updated_at"`
	TargetTypes     []TargetType  `json:"target_types"`
	SystemOwned     bool          `json:"system_owned"`
	Version         int32         `json:"version"`
	ArchivedAt      sql.NullTime  `json:"archived_at"`
	ClosedRequestID int64         `json:"closed_request_id"`
}

// Archiving also closes the template's open edit request in the same
// statement, so no pending edit can outlive (or be approved onto) it.
func (q *Queries) ArchiveFlowTemplate(ctx context.Context, arg ArchiveFlowTemplateParams) (ArchiveFlowTemplateRow, error) {
	row := q.db.QueryRowContext(ctx, archiveFlowTemplate, arg.ID, arg.ReviewerID)
	var i ArchiveFlowTemplateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
		&i.Version,
		&i.ArchivedAt,
		&i.ClosedRequestID,
	)
	return i, err
}

const createFlowTemplate = `-- name: CreateFlowTemplate :one
INSERT INTO flow_templates (
  user_id,
  title,
  text,
  target_types
) VALUES (
  $1::BIGINT,
  $2,
  $3,
  $4
)
RETURNING id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at
`

type CreateFlowTemplateParams struct {
	UserID      int64        `json:"user_id"`
	Title       string       `json:"title"`
	Text        string       `json:"text"`
	TargetTypes []TargetType `json:"target_types"`
}

func (q *Queries) CreateFlowTemplate(ctx context.Context, arg CreateFlowTemplateParams) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, createFlowTemplate,
		arg.UserID,
		arg.Title,
		arg.Text,
		pq.Array(arg.TargetTypes),
	)
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
		&i.Version,
		&i.ArchivedAt,
	)
	return i, err
}

const getDefaultFlowTemplatesByTargetType = `-- name: GetDefaultFlowTemplatesByTargetType :many
SELECT id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at FROM flow_templates
WHERE archived_at IS NULL
  AND (user_id = $1::BIGINT OR system_owned = true)
  AND $2::TARGET_TYPE = ANY(target_types)
ORDER BY system_owned DESC, created_at DESC
`

type GetDefaultFlowTemplatesByTargetTypeParams struct {
	UserID     int64      `json:"user_id"`
	TargetType TargetType `json:"target_type"`
}

// Auto-detect only spawns the platform templates plus the caller's own, so a
// template another user published never runs on someone's scan unselected.
func (q *Queries) GetDefaultFlowTemplatesByTargetType(ctx context.Context, arg GetDefaultFlowTemplatesByTargetTypeParams) ([]FlowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getDefaultFlowTemplatesByTargetType, arg.UserID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTemplate
	for rows.Next() {
		var i FlowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.TargetTypes),
			&i.SystemOwned,
			&i.Version,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowTemplate = `-- name: GetFlowTemplate :one

SELECT id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at FROM flow_templates
WHERE id = $1 AND archived_at IS NULL LIMIT 1
`

// Templates form one shared library: every live (non-archived) template is
// visible to every user. Only reviewed content is ever stored here; proposed
// content lives in flow_template_requests until an admin approves it.
func (q *Queries) GetFlowTemplate(ctx context.Context, id int64) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, getFlowTemplate, id)
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
		&i.Version,
		&i.ArchivedAt,
	)
	return i, err
}

const getFlowTemplates = `-- name: GetFlowTemplates :many
SELECT id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at FROM flow_templates
WHERE archived_at IS NULL
ORDER BY system_owned DESC, created_at DESC
`

func (q *Queries) GetFlowTemplates(ctx context.Context) ([]FlowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getFlowTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTemplate
	for rows.Next() {
		var i FlowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.TargetTypes),
			&i.SystemOwned,
			&i.Version,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowTemplatesByTargetType = `-- name: GetFlowTemplatesByTargetType :many
SELECT id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at FROM flow_templates
WHERE archived_at IS NULL
  AND $1::TARGET_TYPE = ANY(target_types)
ORDER BY system_owned DESC, created_at DESC
`

func (q *Queries) GetFlowTemplatesByTargetType(ctx context.Context, targetType TargetType) ([]FlowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getFlowTemplatesByTargetType, targetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTemplate
	for rows.Next() {
		var i FlowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.TargetTypes),
			&i.SystemOwned,
			&i.Version,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowTemplate = `-- name: UpdateFlowTemplate :one
UPDATE flow_templates
SET
  title = $1,
  text = $2,
  target_types = $3,
  version = version + 1
WHERE id = $4
  AND archived_at IS NULL
  AND ($5::INTEGER IS NULL OR version = $5::INTEGER)
RETURNING id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at
`

type UpdateFlowTemplateParams struct {
	Title           string        `json:"title"`
	Text            string        `json:"text"`
	TargetTypes     []TargetType  `json:"target_types"`
	ID              int64         `json:"id"`
	ExpectedVersion sql.NullInt32 `json:"expected_version"`
}

// expected_version is optional: when given, the write only applies if nobody
// changed the template since the editor loaded it.
func (q *Queries) UpdateFlowTemplate(ctx context.Context, arg UpdateFlowTemplateParams) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateFlowTemplate,
		arg.Title,
		arg.Text,
		pq.Array(arg.TargetTypes),
		arg.ID,
		arg.ExpectedVersion,
	)
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
		&i.Version,
		&i.ArchivedAt,
	)
	return i, err
}

const updateFlowTemplateTargetTypes = `-- name: UpdateFlowTemplateTargetTypes :one
UPDATE flow_templates
SET
  target_types = $2,
  version = version + 1
WHERE id = $1 AND archived_at IS NULL
RETURNING id, user_id, title, text, created_at, updated_at, target_types, system_owned, version, archived_at
`

type UpdateFlowTemplateTargetTypesParams struct {
	ID          int64        `json:"id"`
	TargetTypes []TargetType `json:"target_types"`
}

func (q *Queries) UpdateFlowTemplateTargetTypes(ctx context.Context, arg UpdateFlowTemplateTargetTypesParams) (FlowTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateFlowTemplateTargetTypes, arg.ID, pq.Array(arg.TargetTypes))
	var i FlowTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.TargetTypes),
		&i.SystemOwned,
		&i.Version,
		&i.ArchivedAt,
	)
	return i, err
}
