// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: providers.sql

package database

import (
	"context"
	"encoding/json"
)

const clearDefaultProviders = `-- name: ClearDefaultProviders :exec
UPDATE providers SET is_default = false
WHERE is_default = true AND deleted_at IS NULL
`

func (q *Queries) ClearDefaultProviders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultProviders)
	return err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
  user_id,
  type,
  name,
  config
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, type, name, config, created_at, updated_at, deleted_at, is_default
`

type CreateProviderParams struct {
	UserID int64           `json:"user_id"`
	Type   ProviderType    `json:"type"`
	Name   string          `json:"name"`
	Config json.RawMessage `json:"config"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, createProvider,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Config,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDefault,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :one
UPDATE providers
SET deleted_at = CURRENT_TIMESTAMP, is_default = false
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, type, name, config, created_at, updated_at, deleted_at, is_default
`

func (q *Queries) DeleteProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRowContext(ctx, deleteProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDefault,
	)
	return i, err
}

const getDefaultProvider = `-- name: GetDefaultProvider :one
SELECT id, user_id, type, name, config, created_at, updated_at, deleted_at, is_default FROM providers
WHERE is_default = true AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDefaultProvider(ctx context.Context) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getDefaultProvider)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDefault,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT
  p.id, p.user_id, p.type, p.name, p.config, p.created_at, p.updated_at, p.deleted_at, p.is_default
FROM providers p
WHERE p.id = $1 AND p.deleted_at IS NULL
`

func (q *Queries) GetProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDefault,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT
  p.id, p.user_id, p.type, p.name, p.config, p.created_at, p.updated_at, p.deleted_at, p.is_default
FROM providers p
WHERE p.name = $1 AND p.deleted_at IS NULL
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByName, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDefault,
	)
	return i, err
}

const getProviders = `-- name: GetProviders :many
SELECT
  p.id, p.user_id, p.type, p.name, p.config, p.created_at, p.updated_at, p.deleted_at, p.is_default
FROM providers p
WHERE p.deleted_at IS NULL
ORDER BY p.created_at ASC
`

// Providers are shared by all users; user_id only records the admin who
// created the row, so no query here is scoped to a user.
func (q *Queries) GetProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, getProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvidersByType = `-- name: GetProvidersByType :many
SELECT
  p.id, p.user_id, p.type, p.name, p.config, p.created_at, p.updated_at, p.deleted_at, p.is_default
FROM providers p
WHERE p.type = $1 AND p.deleted_at IS NULL
ORDER BY p.created_at ASC
`

func (q *Queries) GetProvidersByType(ctx context.Context, type_ ProviderType) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, getProvidersByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultProvider = `-- name: SetDefaultProvider :one
UPDATE providers SET is_default = true
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, type, name, config, created_at, updated_at, deleted_at, is_default
`

func (q *Queries) SetDefaultProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRowContext(ctx, setDefaultProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDefault,
	)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET config = $2, name = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, type, name, config, created_at, updated_at, deleted_at, is_default
`

type UpdateProviderParams struct {
	ID     int64           `json:"id"`
	Config json.RawMessage `json:"config"`
	Name   string          `json:"name"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, updateProvider, arg.ID, arg.Config, arg.Name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsDefault,
	)
	return i, err
}
