// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddFavoriteFlow(ctx context.Context, arg AddFavoriteFlowParams) (UserPreference, error)
	// Approving a new template: mark the request approved and publish the
	// template atomically. The template id is drawn up front so the request can
	// link to the template it produced within the same statement.
	ApproveCreateFlowTemplateRequest(ctx context.Context, arg ApproveCreateFlowTemplateRequestParams) (FlowTemplate, error)
	// Approving an edit: the template is written first, guarded on its version
	// (re-checked by Postgres after any row-lock wait), and the request is marked
	// approved only if that write happened. A concurrent admin edit, archive,
	// requester edit or second reviewer therefore makes this a no-op, never a
	// half-applied approval.
	ApproveUpdateFlowTemplateRequest(ctx context.Context, arg ApproveUpdateFlowTemplateRequestParams) (ApproveUpdateFlowTemplateRequestRow, error)
	// Archiving also closes the template's open edit request in the same
	// statement, so no pending edit can outlive (or be approved onto) it.
	ArchiveFlowTemplate(ctx context.Context, arg ArchiveFlowTemplateParams) (ArchiveFlowTemplateRow, error)
	ClearDefaultProviders(ctx context.Context, userID int64) error
	CountActiveDomainsForUser(ctx context.Context, userID int64) (int64, error)
	CountActiveFlowsForUser(ctx context.Context, userID int64) (int64, error)
	CountPendingFlowTemplateRequestsByRequester(ctx context.Context, requesterID int64) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAgentLog(ctx context.Context, arg CreateAgentLogParams) (Agentlog, error)
	CreateAssistant(ctx context.Context, arg CreateAssistantParams) (Assistant, error)
	CreateAssistantLog(ctx context.Context, arg CreateAssistantLogParams) (Assistantlog, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	// Pentest chat. Every session query is scoped by user_id: sessions are
	// private to their owner, and there is no admin view.
	CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error)
	CreateChatUsage(ctx context.Context, arg CreateChatUsageParams) (ChatUsage, error)
	CreateContainer(ctx context.Context, arg CreateContainerParams) (Container, error)
	CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error)
	CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error)
	CreateFlowTemplate(ctx context.Context, arg CreateFlowTemplateParams) (FlowTemplate, error)
	CreateFlowTemplateRequest(ctx context.Context, arg CreateFlowTemplateRequestParams) (FlowTemplateRequest, error)
	CreateMsgChain(ctx context.Context, arg CreateMsgChainParams) (Msgchain, error)
	CreateMsgLog(ctx context.Context, arg CreateMsgLogParams) (Msglog, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateResultAssistantLog(ctx context.Context, arg CreateResultAssistantLogParams) (Assistantlog, error)
	CreateResultMsgLog(ctx context.Context, arg CreateResultMsgLogParams) (Msglog, error)
	// ciphertext must already be AES-256-GCM encrypted by pkg/crypt before insert;
	// the plaintext credential must NEVER be passed here.
	CreateScanCredential(ctx context.Context, arg CreateScanCredentialParams) (ScanCredential, error)
	CreateScreenshot(ctx context.Context, arg CreateScreenshotParams) (Screenshot, error)
	CreateSearchLog(ctx context.Context, arg CreateSearchLogParams) (Searchlog, error)
	CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTermLog(ctx context.Context, arg CreateTermLogParams) (Termlog, error)
	CreateToolcall(ctx context.Context, arg CreateToolcallParams) (Toolcall, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error)
	CreateUserPrompt(ctx context.Context, arg CreateUserPromptParams) (Prompt, error)
	CreateVectorStoreLog(ctx context.Context, arg CreateVectorStoreLogParams) (Vecstorelog, error)
	DeleteAPIToken(ctx context.Context, id int64) (ApiToken, error)
	DeleteAssistant(ctx context.Context, id int64) (Assistant, error)
	DeleteDomain(ctx context.Context, id int64) (Domain, error)
	DeleteFavoriteFlow(ctx context.Context, arg DeleteFavoriteFlowParams) (UserPreference, error)
	DeleteFlow(ctx context.Context, id int64) (Flow, error)
	DeleteFlowAssistantLog(ctx context.Context, id int64) error
	DeletePrompt(ctx context.Context, id int64) error
	DeleteProvider(ctx context.Context, id int64) (Provider, error)
	DeleteScanCredentialsForDomain(ctx context.Context, domainID int64) error
	DeleteSubtask(ctx context.Context, id int64) error
	DeleteSubtasks(ctx context.Context, ids []int64) error
	// A reply that failed before the provider billed anything gives the user
	// their message back.
	DeleteUnbilledChatUsageByMessage(ctx context.Context, messageID sql.NullInt64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserAPIToken(ctx context.Context, arg DeleteUserAPITokenParams) (ApiToken, error)
	DeleteUserAPITokenByTokenID(ctx context.Context, arg DeleteUserAPITokenByTokenIDParams) (ApiToken, error)
	DeleteUserChatSession(ctx context.Context, arg DeleteUserChatSessionParams) (ChatSession, error)
	DeleteUserPreferences(ctx context.Context, userID int64) error
	DeleteUserPrompt(ctx context.Context, arg DeleteUserPromptParams) error
	DeleteUserProvider(ctx context.Context, arg DeleteUserProviderParams) (Provider, error)
	// Replies cannot outlive the process that streams them: anything still
	// streaming at startup was cut off by a restart.
	FailStreamingChatMessages(ctx context.Context) error
	// Final write of a reply. Guarded on 'streaming' so a stop and a finish
	// racing each other cannot overwrite the one that landed first.
	FinishChatMessage(ctx context.Context, arg FinishChatMessageParams) (ChatMessage, error)
	GetAPIToken(ctx context.Context, id int64) (ApiToken, error)
	GetAPITokenByTokenID(ctx context.Context, tokenID string) (ApiToken, error)
	GetAPITokens(ctx context.Context) ([]ApiToken, error)
	GetActiveScanCredentialForDomain(ctx context.Context, domainID int64) (ScanCredential, error)
	// Get toolcalls stats for all flows
	GetAllFlowsToolcallsStats(ctx context.Context) ([]GetAllFlowsToolcallsStatsRow, error)
	GetAllFlowsUsageStats(ctx context.Context) ([]GetAllFlowsUsageStatsRow, error)
	GetAssistant(ctx context.Context, id int64) (Assistant, error)
	GetAssistantUseAgents(ctx context.Context, id int64) (bool, error)
	// Get total count of assistants for a specific flow
	GetAssistantsCountForFlow(ctx context.Context, flowID int64) (int64, error)
	GetCallToolcall(ctx context.Context, callID string) (Toolcall, error)
	GetChatMessages(ctx context.Context, sessionID int64) ([]ChatMessage, error)
	// Messages not yet folded into the session summary, oldest first.
	GetChatMessagesAfter(ctx context.Context, arg GetChatMessagesAfterParams) ([]ChatMessage, error)
	GetContainerTermLogs(ctx context.Context, containerID int64) ([]Termlog, error)
	GetContainers(ctx context.Context) ([]Container, error)
	// Auto-detect only spawns the platform templates plus the caller's own, so a
	// template another user published never runs on someone's scan unselected.
	GetDefaultFlowTemplatesByTargetType(ctx context.Context, arg GetDefaultFlowTemplatesByTargetTypeParams) ([]FlowTemplate, error)
	GetDefaultProvider(ctx context.Context, userID int64) (Provider, error)
	GetDomain(ctx context.Context, id int64) (Domain, error)
	GetDomains(ctx context.Context) ([]Domain, error)
	GetFlow(ctx context.Context, id int64) (Flow, error)
	GetFlowAgentLog(ctx context.Context, arg GetFlowAgentLogParams) (Agentlog, error)
	GetFlowAgentLogs(ctx context.Context, flowID int64) ([]Agentlog, error)
	GetFlowAssistant(ctx context.Context, arg GetFlowAssistantParams) (Assistant, error)
	GetFlowAssistantLog(ctx context.Context, id int64) (Assistantlog, error)
	GetFlowAssistantLogs(ctx context.Context, arg GetFlowAssistantLogsParams) ([]Assistantlog, error)
	GetFlowAssistants(ctx context.Context, flowID int64) ([]Assistant, error)
	GetFlowContainers(ctx context.Context, flowID int64) ([]Container, error)
	GetFlowFindings(ctx context.Context, flowID int64) ([]GetFlowFindingsRow, error)
	GetFlowMsgChains(ctx context.Context, flowID int64) ([]Msgchain, error)
	GetFlowMsgLogs(ctx context.Context, flowID int64) ([]Msglog, error)
	GetFlowPrimaryContainer(ctx context.Context, flowID int64) (Container, error)
	GetFlowScreenshots(ctx context.Context, flowID int64) ([]Screenshot, error)
	GetFlowSearchLog(ctx context.Context, arg GetFlowSearchLogParams) (Searchlog, error)
	GetFlowSearchLogs(ctx context.Context, flowID int64) ([]Searchlog, error)
	// ==================== Flows Analytics Queries ====================
	// Get total count of tasks, subtasks, and assistants for a specific flow
	GetFlowStats(ctx context.Context, id int64) (GetFlowStatsRow, error)
	GetFlowSubtask(ctx context.Context, arg GetFlowSubtaskParams) (Subtask, error)
	GetFlowSubtasks(ctx context.Context, flowID int64) ([]Subtask, error)
	GetFlowTask(ctx context.Context, arg GetFlowTaskParams) (Task, error)
	GetFlowTaskSubtasks(ctx context.Context, arg GetFlowTaskSubtasksParams) ([]Subtask, error)
	GetFlowTaskTypeLastMsgChain(ctx context.Context, arg GetFlowTaskTypeLastMsgChainParams) (Msgchain, error)
	GetFlowTasks(ctx context.Context, flowID int64) ([]Task, error)
	// Templates form one shared library: every live (non-archived) template is
	// visible to every user. Only reviewed content is ever stored here; proposed
	// content lives in flow_template_requests until an admin approves it.
	GetFlowTemplate(ctx context.Context, id int64) (FlowTemplate, error)
	// Template requests: a user's proposed new template or edit to their own
	// template, waiting for admin review. Every state transition is a single
	// conditional statement (status/revision/version guards in the WHERE clause),
	// so concurrent reviewers or a requester editing mid-review can never apply a
	// decision to content the reviewer did not see.
	GetFlowTemplateRequest(ctx context.Context, id int64) (FlowTemplateRequestsView, error)
	GetFlowTemplateRequests(ctx context.Context) ([]FlowTemplateRequestsView, error)
	GetFlowTemplateRequestsByRequester(ctx context.Context, requesterID int64) ([]FlowTemplateRequestsView, error)
	GetFlowTemplates(ctx context.Context) ([]FlowTemplate, error)
	GetFlowTemplatesByTargetType(ctx context.Context, targetType TargetType) ([]FlowTemplate, error)
	GetFlowTermLogs(ctx context.Context, flowID int64) ([]Termlog, error)
	// ==================== Toolcalls Analytics Queries ====================
	// Get total execution time and count of toolcalls for a specific flow
	GetFlowToolcallsStats(ctx context.Context, flowID int64) (GetFlowToolcallsStatsRow, error)
	GetFlowTypeMsgChains(ctx context.Context, arg GetFlowTypeMsgChainsParams) ([]Msgchain, error)
	GetFlowUsageStats(ctx context.Context, flowID int64) (GetFlowUsageStatsRow, error)
	GetFlowVectorStoreLog(ctx context.Context, arg GetFlowVectorStoreLogParams) (Vecstorelog, error)
	GetFlowVectorStoreLogs(ctx context.Context, flowID int64) ([]Vecstorelog, error)
	GetFlows(ctx context.Context) ([]Flow, error)
	GetFlowsForDomain(ctx context.Context, domainID sql.NullInt64) ([]Flow, error)
	// Get flow IDs created in the last 3 months for analytics
	GetFlowsForPeriodLast3Months(ctx context.Context, userID int64) ([]GetFlowsForPeriodLast3MonthsRow, error)
	// Get flow IDs created in the last month for analytics
	GetFlowsForPeriodLastMonth(ctx context.Context, userID int64) ([]GetFlowsForPeriodLastMonthRow, error)
	// Get flow IDs created in the last week for analytics
	GetFlowsForPeriodLastWeek(ctx context.Context, userID int64) ([]GetFlowsForPeriodLastWeekRow, error)
	// Get flows stats by day for the last 3 months
	GetFlowsStatsByDayLast3Months(ctx context.Context, userID int64) ([]GetFlowsStatsByDayLast3MonthsRow, error)
	// Get flows stats by day for the last month
	GetFlowsStatsByDayLastMonth(ctx context.Context, userID int64) ([]GetFlowsStatsByDayLastMonthRow, error)
	// Get flows stats by day for the last week
	GetFlowsStatsByDayLastWeek(ctx context.Context, userID int64) ([]GetFlowsStatsByDayLastWeekRow, error)
	GetMsgChain(ctx context.Context, id int64) (Msgchain, error)
	// Get all msgchains for a flow (including task and subtask level)
	GetMsgchainsForFlow(ctx context.Context, flowID int64) ([]GetMsgchainsForFlowRow, error)
	GetPendingFlowTemplateRequestByTemplate(ctx context.Context, templateID sql.NullInt64) (FlowTemplateRequestsView, error)
	GetPrompts(ctx context.Context) ([]Prompt, error)
	GetProvider(ctx context.Context, id int64) (Provider, error)
	GetProviders(ctx context.Context) ([]Provider, error)
	GetProvidersByType(ctx context.Context, type_ ProviderType) ([]Provider, error)
	GetRole(ctx context.Context, id int64) (GetRoleRow, error)
	GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error)
	GetRoles(ctx context.Context) ([]GetRolesRow, error)
	GetRunningContainers(ctx context.Context) ([]Container, error)
	GetScreenshot(ctx context.Context, id int64) (Screenshot, error)
	GetSubtask(ctx context.Context, id int64) (Subtask, error)
	GetSubtaskAgentLogs(ctx context.Context, subtaskID sql.NullInt64) ([]Agentlog, error)
	GetSubtaskMsgChains(ctx context.Context, subtaskID sql.NullInt64) ([]Msgchain, error)
	GetSubtaskMsgLogs(ctx context.Context, subtaskID sql.NullInt64) ([]Msglog, error)
	GetSubtaskPrimaryMsgChains(ctx context.Context, subtaskID sql.NullInt64) ([]Msgchain, error)
	GetSubtaskScreenshots(ctx context.Context, subtaskID sql.NullInt64) ([]Screenshot, error)
	GetSubtaskSearchLogs(ctx context.Context, subtaskID sql.NullInt64) ([]Searchlog, error)
	GetSubtaskTermLogs(ctx context.Context, subtaskID sql.NullInt64) ([]Termlog, error)
	GetSubtaskToolcalls(ctx context.Context, subtaskID sql.NullInt64) ([]Toolcall, error)
	// Get total execution time and count of toolcalls for a specific subtask
	GetSubtaskToolcallsStats(ctx context.Context, subtaskID sql.NullInt64) (GetSubtaskToolcallsStatsRow, error)
	GetSubtaskTypeMsgChains(ctx context.Context, arg GetSubtaskTypeMsgChainsParams) ([]Msgchain, error)
	GetSubtaskUsageStats(ctx context.Context, subtaskID sql.NullInt64) (GetSubtaskUsageStatsRow, error)
	GetSubtaskVectorStoreLogs(ctx context.Context, subtaskID sql.NullInt64) ([]Vecstorelog, error)
	// Get all subtasks for multiple tasks
	GetSubtasksForTasks(ctx context.Context, taskIds []int64) ([]GetSubtasksForTasksRow, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	GetTaskAgentLogs(ctx context.Context, taskID sql.NullInt64) ([]Agentlog, error)
	GetTaskCompletedSubtasks(ctx context.Context, taskID int64) ([]Subtask, error)
	GetTaskMsgChains(ctx context.Context, taskID sql.NullInt64) ([]Msgchain, error)
	GetTaskMsgLogs(ctx context.Context, taskID sql.NullInt64) ([]Msglog, error)
	GetTaskPlannedSubtasks(ctx context.Context, taskID int64) ([]Subtask, error)
	GetTaskPrimaryMsgChainIDs(ctx context.Context, taskID sql.NullInt64) ([]GetTaskPrimaryMsgChainIDsRow, error)
	GetTaskPrimaryMsgChains(ctx context.Context, taskID sql.NullInt64) ([]Msgchain, error)
	GetTaskScreenshots(ctx context.Context, taskID sql.NullInt64) ([]Screenshot, error)
	GetTaskSearchLogs(ctx context.Context, taskID sql.NullInt64) ([]Searchlog, error)
	GetTaskSubtasks(ctx context.Context, taskID int64) ([]Subtask, error)
	GetTaskTermLogs(ctx context.Context, taskID sql.NullInt64) ([]Termlog, error)
	// Get total execution time and count of toolcalls for a specific task
	GetTaskToolcallsStats(ctx context.Context, taskID sql.NullInt64) (GetTaskToolcallsStatsRow, error)
	GetTaskTypeMsgChains(ctx context.Context, arg GetTaskTypeMsgChainsParams) ([]Msgchain, error)
	GetTaskUsageStats(ctx context.Context, taskID sql.NullInt64) (GetTaskUsageStatsRow, error)
	GetTaskVectorStoreLogs(ctx context.Context, taskID sql.NullInt64) ([]Vecstorelog, error)
	// Get all tasks for a flow
	GetTasksForFlow(ctx context.Context, flowID int64) ([]GetTasksForFlowRow, error)
	GetTermLog(ctx context.Context, id int64) (Termlog, error)
	// Get all toolcalls for a flow
	GetToolcallsForFlow(ctx context.Context, flowID int64) ([]GetToolcallsForFlowRow, error)
	// Get toolcalls stats by day for the last 3 months
	GetToolcallsStatsByDayLast3Months(ctx context.Context, userID int64) ([]GetToolcallsStatsByDayLast3MonthsRow, error)
	// Get toolcalls stats by day for the last month
	GetToolcallsStatsByDayLastMonth(ctx context.Context, userID int64) ([]GetToolcallsStatsByDayLastMonthRow, error)
	// Get toolcalls stats by day for the last week
	GetToolcallsStatsByDayLastWeek(ctx context.Context, userID int64) ([]GetToolcallsStatsByDayLastWeekRow, error)
	// Get toolcalls stats grouped by function name for a user
	GetToolcallsStatsByFunction(ctx context.Context, userID int64) ([]GetToolcallsStatsByFunctionRow, error)
	// Get toolcalls stats grouped by function name for a specific flow
	GetToolcallsStatsByFunctionForFlow(ctx context.Context, flowID int64) ([]GetToolcallsStatsByFunctionForFlowRow, error)
	GetUsageStatsByDayLast3Months(ctx context.Context, userID int64) ([]GetUsageStatsByDayLast3MonthsRow, error)
	GetUsageStatsByDayLastMonth(ctx context.Context, userID int64) ([]GetUsageStatsByDayLastMonthRow, error)
	GetUsageStatsByDayLastWeek(ctx context.Context, userID int64) ([]GetUsageStatsByDayLastWeekRow, error)
	GetUsageStatsByModel(ctx context.Context, userID int64) ([]GetUsageStatsByModelRow, error)
	GetUsageStatsByProvider(ctx context.Context, userID int64) ([]GetUsageStatsByProviderRow, error)
	GetUsageStatsByType(ctx context.Context, userID int64) ([]GetUsageStatsByTypeRow, error)
	GetUsageStatsByTypeForFlow(ctx context.Context, flowID int64) ([]GetUsageStatsByTypeForFlowRow, error)
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	GetUserAPIToken(ctx context.Context, arg GetUserAPITokenParams) (ApiToken, error)
	GetUserAPITokenByTokenID(ctx context.Context, arg GetUserAPITokenByTokenIDParams) (ApiToken, error)
	GetUserAPITokens(ctx context.Context, userID int64) ([]ApiToken, error)
	GetUserByHash(ctx context.Context, hash string) (GetUserByHashRow, error)
	GetUserChatMessage(ctx context.Context, arg GetUserChatMessageParams) (ChatMessage, error)
	GetUserChatReplyStats(ctx context.Context, arg GetUserChatReplyStatsParams) (GetUserChatReplyStatsRow, error)
	GetUserChatSession(ctx context.Context, arg GetUserChatSessionParams) (ChatSession, error)
	GetUserChatSessions(ctx context.Context, userID int64) ([]ChatSession, error)
	GetUserChatTokenStats(ctx context.Context, arg GetUserChatTokenStatsParams) (GetUserChatTokenStatsRow, error)
	GetUserContainers(ctx context.Context, userID int64) ([]Container, error)
	GetUserDomain(ctx context.Context, arg GetUserDomainParams) (Domain, error)
	GetUserDomains(ctx context.Context, userID int64) ([]Domain, error)
	GetUserFlow(ctx context.Context, arg GetUserFlowParams) (Flow, error)
	GetUserFlowAgentLogs(ctx context.Context, arg GetUserFlowAgentLogsParams) ([]Agentlog, error)
	GetUserFlowAssistant(ctx context.Context, arg GetUserFlowAssistantParams) (Assistant, error)
	GetUserFlowAssistantLogs(ctx context.Context, arg GetUserFlowAssistantLogsParams) ([]Assistantlog, error)
	GetUserFlowAssistants(ctx context.Context, arg GetUserFlowAssistantsParams) ([]Assistant, error)
	GetUserFlowContainers(ctx context.Context, arg GetUserFlowContainersParams) ([]Container, error)
	GetUserFlowMsgLogs(ctx context.Context, arg GetUserFlowMsgLogsParams) ([]Msglog, error)
	GetUserFlowScreenshots(ctx context.Context, arg GetUserFlowScreenshotsParams) ([]Screenshot, error)
	GetUserFlowSearchLogs(ctx context.Context, arg GetUserFlowSearchLogsParams) ([]Searchlog, error)
	GetUserFlowSubtasks(ctx context.Context, arg GetUserFlowSubtasksParams) ([]Subtask, error)
	GetUserFlowTask(ctx context.Context, arg GetUserFlowTaskParams) (Task, error)
	GetUserFlowTaskSubtasks(ctx context.Context, arg GetUserFlowTaskSubtasksParams) ([]Subtask, error)
	GetUserFlowTasks(ctx context.Context, arg GetUserFlowTasksParams) ([]Task, error)
	GetUserFlowTermLogs(ctx context.Context, arg GetUserFlowTermLogsParams) ([]Termlog, error)
	GetUserFlowVectorStoreLogs(ctx context.Context, arg GetUserFlowVectorStoreLogsParams) ([]Vecstorelog, error)
	GetUserFlows(ctx context.Context, userID int64) ([]Flow, error)
	GetUserPreferencesByUserID(ctx context.Context, userID int64) (UserPreference, error)
	GetUserPrompt(ctx context.Context, arg GetUserPromptParams) (Prompt, error)
	GetUserPromptByType(ctx context.Context, arg GetUserPromptByTypeParams) (Prompt, error)
	GetUserPrompts(ctx context.Context, userID int64) ([]Prompt, error)
	GetUserProvider(ctx context.Context, arg GetUserProviderParams) (Provider, error)
	GetUserProviderByName(ctx context.Context, arg GetUserProviderByNameParams) (Provider, error)
	GetUserProviders(ctx context.Context, userID int64) ([]Provider, error)
	GetUserProvidersByType(ctx context.Context, arg GetUserProvidersByTypeParams) ([]Provider, error)
	// Get total count of flows, tasks, subtasks, and assistants for a user
	GetUserTotalFlowsStats(ctx context.Context, userID int64) (GetUserTotalFlowsStatsRow, error)
	// Get total toolcalls stats for a user
	GetUserTotalToolcallsStats(ctx context.Context, userID int64) (GetUserTotalToolcallsStatsRow, error)
	GetUserTotalUsageStats(ctx context.Context, userID int64) (GetUserTotalUsageStatsRow, error)
	GetUsers(ctx context.Context) ([]GetUsersRow, error)
	RejectFlowTemplateRequest(ctx context.Context, arg RejectFlowTemplateRequestParams) (FlowTemplateRequest, error)
	// Replaces the placeholder title with a generated one, unless the user
	// renamed the session in the meantime.
	ReplaceChatSessionTitle(ctx context.Context, arg ReplaceChatSessionTitleParams) (ChatSession, error)
	SetDefaultProvider(ctx context.Context, arg SetDefaultProviderParams) (Provider, error)
	SetDomainScopeBox(ctx context.Context, arg SetDomainScopeBoxParams) error
	SetFlowDomain(ctx context.Context, arg SetFlowDomainParams) error
	// Records the provider of the latest message; also bumps updated_at so the
	// session moves to the top of the history list.
	TouchChatSession(ctx context.Context, arg TouchChatSessionParams) (ChatSession, error)
	UpdateAPIToken(ctx context.Context, arg UpdateAPITokenParams) (ApiToken, error)
	UpdateAssistant(ctx context.Context, arg UpdateAssistantParams) (Assistant, error)
	UpdateAssistantFindings(ctx context.Context, arg UpdateAssistantFindingsParams) error
	UpdateAssistantLanguage(ctx context.Context, arg UpdateAssistantLanguageParams) (Assistant, error)
	UpdateAssistantLog(ctx context.Context, arg UpdateAssistantLogParams) (Assistantlog, error)
	UpdateAssistantLogContent(ctx context.Context, arg UpdateAssistantLogContentParams) (Assistantlog, error)
	UpdateAssistantLogResult(ctx context.Context, arg UpdateAssistantLogResultParams) (Assistantlog, error)
	UpdateAssistantModel(ctx context.Context, arg UpdateAssistantModelParams) (Assistant, error)
	UpdateAssistantStatus(ctx context.Context, arg UpdateAssistantStatusParams) (Assistant, error)
	UpdateAssistantTitle(ctx context.Context, arg UpdateAssistantTitleParams) (Assistant, error)
	UpdateAssistantToolCallIDTemplate(ctx context.Context, arg UpdateAssistantToolCallIDTemplateParams) (Assistant, error)
	UpdateAssistantUseAgents(ctx context.Context, arg UpdateAssistantUseAgentsParams) (Assistant, error)
	UpdateChatSessionSummary(ctx context.Context, arg UpdateChatSessionSummaryParams) (ChatSession, error)
	UpdateChatUsageByMessage(ctx context.Context, arg UpdateChatUsageByMessageParams) error
	UpdateContainerImage(ctx context.Context, arg UpdateContainerImageParams) (Container, error)
	UpdateContainerStatus(ctx context.Context, arg UpdateContainerStatusParams) (Container, error)
	UpdateContainerStatusLocalID(ctx context.Context, arg UpdateContainerStatusLocalIDParams) (Container, error)
	UpdateDomainDetectionMetadata(ctx context.Context, arg UpdateDomainDetectionMetadataParams) (Domain, error)
	UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) (Domain, error)
	UpdateFlow(ctx context.Context, arg UpdateFlowParams) (Flow, error)
	UpdateFlowLanguage(ctx context.Context, arg UpdateFlowLanguageParams) (Flow, error)
	UpdateFlowProvider(ctx context.Context, arg UpdateFlowProviderParams) (Flow, error)
	UpdateFlowStatus(ctx context.Context, arg UpdateFlowStatusParams) (Flow, error)
	// expected_version is optional: when given, the write only applies if nobody
	// changed the template since the editor loaded it.
	UpdateFlowTemplate(ctx context.Context, arg UpdateFlowTemplateParams) (FlowTemplate, error)
	UpdateFlowTemplateTargetTypes(ctx context.Context, arg UpdateFlowTemplateTargetTypesParams) (FlowTemplate, error)
	UpdateFlowTitle(ctx context.Context, arg UpdateFlowTitleParams) (Flow, error)
	UpdateFlowToolCallIDTemplate(ctx context.Context, arg UpdateFlowToolCallIDTemplateParams) (Flow, error)
	UpdateMsgChain(ctx context.Context, arg UpdateMsgChainParams) (Msgchain, error)
	UpdateMsgChainUsage(ctx context.Context, arg UpdateMsgChainUsageParams) (Msgchain, error)
	UpdateMsgLogResult(ctx context.Context, arg UpdateMsgLogResultParams) (Msglog, error)
	UpdatePendingFlowTemplateRequest(ctx context.Context, arg UpdatePendingFlowTemplateRequestParams) (FlowTemplateRequest, error)
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) (Prompt, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateSubtaskContext(ctx context.Context, arg UpdateSubtaskContextParams) (Subtask, error)
	UpdateSubtaskFailedResult(ctx context.Context, arg UpdateSubtaskFailedResultParams) (Subtask, error)
	UpdateSubtaskFinishedResult(ctx context.Context, arg UpdateSubtaskFinishedResultParams) (Subtask, error)
	UpdateSubtaskResult(ctx context.Context, arg UpdateSubtaskResultParams) (Subtask, error)
	UpdateSubtaskStatus(ctx context.Context, arg UpdateSubtaskStatusParams) (Subtask, error)
	UpdateTaskFailedResult(ctx context.Context, arg UpdateTaskFailedResultParams) (Task, error)
	UpdateTaskFindings(ctx context.Context, arg UpdateTaskFindingsParams) error
	UpdateTaskFinishedResult(ctx context.Context, arg UpdateTaskFinishedResultParams) (Task, error)
	UpdateTaskResult(ctx context.Context, arg UpdateTaskResultParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateToolcallFailedResult(ctx context.Context, arg UpdateToolcallFailedResultParams) (Toolcall, error)
	UpdateToolcallFinishedResult(ctx context.Context, arg UpdateToolcallFinishedResultParams) (Toolcall, error)
	UpdateToolcallStatus(ctx context.Context, arg UpdateToolcallStatusParams) (Toolcall, error)
	UpdateUserAPIToken(ctx context.Context, arg UpdateUserAPITokenParams) (ApiToken, error)
	UpdateUserChatSessionTitle(ctx context.Context, arg UpdateUserChatSessionTitleParams) (ChatSession, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserPasswordChangeRequired(ctx context.Context, arg UpdateUserPasswordChangeRequiredParams) (User, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error)
	UpdateUserPrompt(ctx context.Context, arg UpdateUserPromptParams) (Prompt, error)
	UpdateUserPromptByType(ctx context.Context, arg UpdateUserPromptByTypeParams) (Prompt, error)
	UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) (Provider, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error)
	WithdrawFlowTemplateRequest(ctx context.Context, arg WithdrawFlowTemplateRequestParams) (FlowTemplateRequest, error)
}

var _ Querier = (*Queries)(nil)
