// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scan_credentials.sql

package database

import (
	"context"
)

const createScanCredential = `-- name: CreateScanCredential :one
INSERT INTO scan_credentials (
  user_id, domain_id, kind, ciphertext
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, domain_id, kind, ciphertext, created_at, updated_at, deleted_at
`

type CreateScanCredentialParams struct {
	UserID     int64  `json:"user_id"`
	DomainID   int64  `json:"domain_id"`
	Kind       string `json:"kind"`
	Ciphertext string `json:"ciphertext"`
}

// ciphertext must already be AES-256-GCM encrypted by pkg/crypt before insert;
// the plaintext credential must NEVER be passed here.
func (q *Queries) CreateScanCredential(ctx context.Context, arg CreateScanCredentialParams) (ScanCredential, error) {
	row := q.db.QueryRowContext(ctx, createScanCredential,
		arg.UserID,
		arg.DomainID,
		arg.Kind,
		arg.Ciphertext,
	)
	var i ScanCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainID,
		&i.Kind,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteScanCredentialsForDomain = `-- name: DeleteScanCredentialsForDomain :exec
UPDATE scan_credentials
SET deleted_at = CURRENT_TIMESTAMP
WHERE domain_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteScanCredentialsForDomain(ctx context.Context, domainID int64) error {
	_, err := q.db.ExecContext(ctx, deleteScanCredentialsForDomain, domainID)
	return err
}

const getActiveScanCredentialForDomain = `-- name: GetActiveScanCredentialForDomain :one
SELECT id, user_id, domain_id, kind, ciphertext, created_at, updated_at, deleted_at FROM scan_credentials
WHERE domain_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveScanCredentialForDomain(ctx context.Context, domainID int64) (ScanCredential, error) {
	row := q.db.QueryRowContext(ctx, getActiveScanCredentialForDomain, domainID)
	var i ScanCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainID,
		&i.Kind,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
